import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './app'
import './style.css'
import { Amplify } from 'aws-amplify';
import awsconfig from './aws-exports'; // Import the awsconfig generated by amplify

Amplify.configure(awsconfig); // Configure Amplify with the generated config


const root = ReactDOM.createRoot(document.getElementById('root')) // Create a root

root.render(
        <App />
)
